name: XL Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    env:
      ARTIFACT_DIR: deploy-artifacts/builds/latest
      DOWNLOAD_ARTIFACT_DIR: download-artifacts/builds/latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JFrog CLI
      uses: jfrog/setup-jfrog-cli@v3
      with:
        version: latest

    - name: Generate timestamp version
      id: version
      run: echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Prepare build artifacts on runner
      run: |
        mkdir -p $ARTIFACT_DIR
        echo "This is a simulated DAR package" > $ARTIFACT_DIR/agate_app.dar
        echo "This is a simulated DAR package" > $ARTIFACT_DIR/agate_app2.dar
        echo "This is a simulated DAR package" > $ARTIFACT_DIR/agate_app3.dar

    - name: Configure JFrog CLI
      run: |
        jfrog config add xl-temp-artifactory \
          --url=https://trial702ns3.jfrog.io \
          --user=${{ secrets.JFROG_USERNAME }} \
          --access-token=${{ secrets.JFROG_TOKEN }} \
          --enc-password=false \
          --overwrite=true \
          --interactive=false

    - name: Upload all DAR files to JFrog (versioned folder) using JFrog CLI
      run: |
        jfrog rt upload "$ARTIFACT_DIR/*.dar" "agate-xl-deploy/builds/${VERSION}/" --flat=true
        
    - name: Download all DAR files from JFrog using JFrog CLI
      run: |
        mkdir -p $DOWNLOAD_ARTIFACT_DIR
        jfrog rt download "agate-xl-deploy/builds/${VERSION}/*.dar" "$DOWNLOAD_ARTIFACT_DIR/" --flat=true
